/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AdminResultBaiDuTranslationResult } from '../models';
/**
 * BaiDuTranslationApi - axios parameter creator
 * @export
 */
export const BaiDuTranslationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 生成前端菜单i18n文件
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiExtendBaiDuTranslationGenerateMenuI18nFilePost: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Extend/baiDuTranslation/generateMenuI18nFile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 生成前端页面i18n文件
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiExtendBaiDuTranslationGeneratePageI18nFilePost: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Extend/baiDuTranslation/generatePageI18nFile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 源语种和目标语种支持：  zh:简体中文  cht:繁體中文(台灣)  yue:繁體中文(香港)  en:英语  de:德语  spa:西班牙语  fin:芬兰语  fra:法语  it:意大利语  jp:日语  kor:韩语  nor:挪威语  pl:波兰语  pt:葡萄牙语  ru:俄语  th:泰语  id:印度尼西亚语  may:马来西亚  vie:越南语    更多语种请查看：https://api.fanyi.baidu.com/doc/21
         * @summary 百度在线翻译
         * @param {string} from 翻译源语种
         * @param {string} to 翻译目标语种
         * @param {string} content 文本内容
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiExtendBaiDuTranslationTranslationGet: async (from: string, to: string, content: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'from' is not null or undefined
            if (from === null || from === undefined) {
                throw new RequiredError('from','Required parameter from was null or undefined when calling apiExtendBaiDuTranslationTranslationGet.');
            }
            // verify required parameter 'to' is not null or undefined
            if (to === null || to === undefined) {
                throw new RequiredError('to','Required parameter to was null or undefined when calling apiExtendBaiDuTranslationTranslationGet.');
            }
            // verify required parameter 'content' is not null or undefined
            if (content === null || content === undefined) {
                throw new RequiredError('content','Required parameter content was null or undefined when calling apiExtendBaiDuTranslationTranslationGet.');
            }
            const localVarPath = `/api/Extend/baiDuTranslation/translation`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = to;
            }

            if (content !== undefined) {
                localVarQueryParameter['content'] = content;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BaiDuTranslationApi - functional programming interface
 * @export
 */
export const BaiDuTranslationApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 生成前端菜单i18n文件
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiExtendBaiDuTranslationGenerateMenuI18nFilePost(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await BaiDuTranslationApiAxiosParamCreator(configuration).apiExtendBaiDuTranslationGenerateMenuI18nFilePost(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 生成前端页面i18n文件
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiExtendBaiDuTranslationGeneratePageI18nFilePost(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await BaiDuTranslationApiAxiosParamCreator(configuration).apiExtendBaiDuTranslationGeneratePageI18nFilePost(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 源语种和目标语种支持：  zh:简体中文  cht:繁體中文(台灣)  yue:繁體中文(香港)  en:英语  de:德语  spa:西班牙语  fin:芬兰语  fra:法语  it:意大利语  jp:日语  kor:韩语  nor:挪威语  pl:波兰语  pt:葡萄牙语  ru:俄语  th:泰语  id:印度尼西亚语  may:马来西亚  vie:越南语    更多语种请查看：https://api.fanyi.baidu.com/doc/21
         * @summary 百度在线翻译
         * @param {string} from 翻译源语种
         * @param {string} to 翻译目标语种
         * @param {string} content 文本内容
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiExtendBaiDuTranslationTranslationGet(from: string, to: string, content: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AdminResultBaiDuTranslationResult>>> {
            const localVarAxiosArgs = await BaiDuTranslationApiAxiosParamCreator(configuration).apiExtendBaiDuTranslationTranslationGet(from, to, content, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * BaiDuTranslationApi - factory interface
 * @export
 */
export const BaiDuTranslationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 生成前端菜单i18n文件
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiExtendBaiDuTranslationGenerateMenuI18nFilePost(options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return BaiDuTranslationApiFp(configuration).apiExtendBaiDuTranslationGenerateMenuI18nFilePost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 生成前端页面i18n文件
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiExtendBaiDuTranslationGeneratePageI18nFilePost(options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return BaiDuTranslationApiFp(configuration).apiExtendBaiDuTranslationGeneratePageI18nFilePost(options).then((request) => request(axios, basePath));
        },
        /**
         * 源语种和目标语种支持：  zh:简体中文  cht:繁體中文(台灣)  yue:繁體中文(香港)  en:英语  de:德语  spa:西班牙语  fin:芬兰语  fra:法语  it:意大利语  jp:日语  kor:韩语  nor:挪威语  pl:波兰语  pt:葡萄牙语  ru:俄语  th:泰语  id:印度尼西亚语  may:马来西亚  vie:越南语    更多语种请查看：https://api.fanyi.baidu.com/doc/21
         * @summary 百度在线翻译
         * @param {string} from 翻译源语种
         * @param {string} to 翻译目标语种
         * @param {string} content 文本内容
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiExtendBaiDuTranslationTranslationGet(from: string, to: string, content: string, options?: AxiosRequestConfig): Promise<AxiosResponse<AdminResultBaiDuTranslationResult>> {
            return BaiDuTranslationApiFp(configuration).apiExtendBaiDuTranslationTranslationGet(from, to, content, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BaiDuTranslationApi - object-oriented interface
 * @export
 * @class BaiDuTranslationApi
 * @extends {BaseAPI}
 */
export class BaiDuTranslationApi extends BaseAPI {
    /**
     * 
     * @summary 生成前端菜单i18n文件
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BaiDuTranslationApi
     */
    public async apiExtendBaiDuTranslationGenerateMenuI18nFilePost(options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return BaiDuTranslationApiFp(this.configuration).apiExtendBaiDuTranslationGenerateMenuI18nFilePost(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary 生成前端页面i18n文件
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BaiDuTranslationApi
     */
    public async apiExtendBaiDuTranslationGeneratePageI18nFilePost(options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return BaiDuTranslationApiFp(this.configuration).apiExtendBaiDuTranslationGeneratePageI18nFilePost(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 源语种和目标语种支持：  zh:简体中文  cht:繁體中文(台灣)  yue:繁體中文(香港)  en:英语  de:德语  spa:西班牙语  fin:芬兰语  fra:法语  it:意大利语  jp:日语  kor:韩语  nor:挪威语  pl:波兰语  pt:葡萄牙语  ru:俄语  th:泰语  id:印度尼西亚语  may:马来西亚  vie:越南语    更多语种请查看：https://api.fanyi.baidu.com/doc/21
     * @summary 百度在线翻译
     * @param {string} from 翻译源语种
     * @param {string} to 翻译目标语种
     * @param {string} content 文本内容
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BaiDuTranslationApi
     */
    public async apiExtendBaiDuTranslationTranslationGet(from: string, to: string, content: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<AdminResultBaiDuTranslationResult>> {
        return BaiDuTranslationApiFp(this.configuration).apiExtendBaiDuTranslationTranslationGet(from, to, content, options).then((request) => request(this.axios, this.basePath));
    }
}
