export default defineEventHandler((event) => {
  return {
    code: 200,
    message: "success",
    timestamp: 1716345000,
    data: [
      {
        id: 1001,
        name: "Home Page",
        status: "published",
        template: "default",
        last_updated: "2025-01-15T10:30:00Z",
        request_path: "/",
        real_path: "pages/index",
        is_dynamic: false,
        title: "Wendy Wu Tours | Award-Winning Tour Specialist",
        description:
          "Discover fully inclusive tours with New Zealand's award-winning specialist. Safe travel plans, visa services included, and expert guides.",
        keywords:
          "tours, new zealand, travel, wendy wu, japan tours, inclusive packages",
        canonical_url: "https://www.wendywutours.co.nz/",
        robots: "index, follow",
        og_title: "Wendy Wu Tours - Exceptional Travel Experiences",
        og_image: "https://cdn.wendywutours.com/assets/og-home.jpg",
        og_type: "website",
        components: [
          {
            id: "comp_unique_001",
            type: "GlobalAlertBar",
            sort_order: 1,
            is_visible: true,
            props: {
              text: "Coronavirus – We are here for you. Read the latest facts and how your travel plans are safe with Wendy Wu Tours",
              linkText: "Read more »",
              linkUrl: "/safety-updates",
              bgColor: "#00a699",
              textColor: "#ffffff",
              icon: "info-circle",
            },
          },
          {
            id: "comp_unique_002",
            type: "TextFeatureSection",
            sort_order: 2,
            is_visible: true,
            props: {
              title: "New Zealand's Award-Winning Tour Specialist",
              features: [
                "Fully inclusive tours",
                "Visa service included",
                "More than 26 years of expertise",
                "Outstanding tour guides",
                "Book with confidence",
              ],
              textAlign: "center",
            },
            styles: {
              paddingTop: "4rem",
              paddingBottom: "4rem",
              backgroundColor: "#fafafa",
            },
          },
          {
            id: "comp_unique_003",
            type: "CmsGridContainer",
            sort_order: 3,
            is_visible: true,
            props: {
            },
            children: [
              {
                id: "PromoCard-001",
                type: "PromoCard",
                sort_order: 1,
                is_visible: true,
                class: "",
                styles: {},
                props: {
                  id: 101,
                  badgeText: "PRIORITY ACCESS",
                  badgeColor: "orange",
                  imgSrc: "https://cdn.wendywutours.com/images/koala-card.jpg",
                  title: "Exclusive release - new tours",
                  description:
                    "We’ve been busy creating new and exciting tours to complement our superb Australia range. Want to know what we’re up to?",
                  btnText: "Register now",
                  btnLink: "/register",
                  analyticsId: "promo_aus_register",
                },
                children: [
                  {
                    id: "badecmsge-003",
                    type: "CmsBadge",
                    sort_order: 2,
                    is_visible: true,
                    styles: {
                      position: "absolute",
                      top: "1rem",
                      right: "1rem",
                      zIndex: 10,
                    },
                    props: {
                      text: "Best Seller",
                    },
                  },
                ],
              },
              {
                id: "PromoCard-002",
                type: "PromoCard",
                sort_order: 1,
                is_visible: true,
                class: "",
                styles: {},
                props: {
                  id: 102,
                  badgeText: "NEW JAPAN BROCHURE",
                  badgeColor: "orange",
                  imgSrc: "https://cdn.wendywutours.com/images/japan-card.jpg",
                  title: "New Japan brochure out now!",
                  description:"Our new interactive brochure has arrived, and we couldn’t be more excited to share it with you! Choose from the classics.",
                  btnText: "Download your free copy",
                  btnLink: "/brochures/japan",
                  analyticsId: "promo_japan_brochure",
                },
              },
              {
                id: "PromoCard-002",
                type: "PromoCard",
                sort_order: 1,
                is_visible: true,
                class: "",
                styles: {},
                props: {
                  id: 102,
                  badgeText: "NEW JAPAN BROCHURE",
                  badgeColor: "orange",
                  imgSrc: "https://cdn.wendywutours.com/images/japan-card.jpg",
                  title: "New Japan brochure out now!",
                  description:
                    "Our new interactive brochure has arrived, and we couldn’t be more excited to share it with you! Choose from the classics.",
                  btnText: "Download your free copy",
                  btnLink: "/brochures/japan",
                  analyticsId: "promo_japan_brochure",
                },
              },
              {
                id: "PromoCard-002",
                type: "PromoCard",
                sort_order: 1,
                is_visible: true,
                class: "",
                styles: {},
                props: {
                  id: 102,
                  badgeText: "NEW JAPAN BROCHURE",
                  badgeColor: "orange",
                  imgSrc: "https://cdn.wendywutours.com/images/japan-card.jpg",
                  title: "New Japan brochure out now!",
                  description:
                    "Our new interactive brochure has arrived, and we couldn’t be more excited to share it with you! Choose from the classics.",
                  btnText: "Download your free copy",
                  btnLink: "/brochures/japan",
                  analyticsId: "promo_japan_brochure",
                },
              },
            ],
          },
        ],
      },
      {
        id: 1002,
        name: "About Page",
        status: "published",
        template: "default",
        last_updated: "2025-01-15T10:30:00Z",
        request_path: "/about",
        real_path: "pages/about",
        is_dynamic: false,
        title: "Wendy Wu Tours | Award-Winning Tour Specialist",
        description:
          "Discover fully inclusive tours with New Zealand's award-winning specialist. Safe travel plans, visa services included, and expert guides.",
        keywords:
          "tours, new zealand, travel, wendy wu, japan tours, inclusive packages",
        canonical_url: "https://www.wendywutours.co.nz/",
        robots: "index, follow",
        og_title: "Wendy Wu Tours - Exceptional Travel Experiences",
        og_image: "https://cdn.wendywutours.com/assets/og-home.jpg",
        og_type: "website",
        json_ld: {
          "@context": "https://schema.org",
          "@type": "TravelAgency",
          name: "Wendy Wu Tours",
          url: "https://www.wendywutours.co.nz",
        },
        page_config: {
          enable_header: true,
          enable_footer: true,
          background_color: "#ffffff",
          custom_css_class: "home-page-wrapper",
        },
        components: [
          {
            id: "comp_unique_002",
            type: "TextFeatureSection",
            sort_order: 2,
            is_visible: true,
            props: {
              title: "New Zealand's Award-Winning Tour Specialist",
              features: [
                "Fully inclusive tours",
                "Visa service included",
                "More than 26 years of expertise",
                "Outstanding tour guides",
                "Book with confidence",
              ],
              textAlign: "center",
            },
            styles: {
              paddingTop: "4rem",
              paddingBottom: "4rem",
              backgroundColor: "#fafafa",
            },
          },
          {
            id: "block_002",
            type: "block@v2",
            sort_order: 2,
            is_visible: true,
            props: {
              title: "Discover Japan with Confidence2222222222222",
              subtitle: "Award-winning tours since 1998",
              backgroundImage: "https://cdn.example.com/images/hero-japan.jpg",
            },
          },
          {
            id: "block_002",
            type: "blockv2@v2",
            sort_order: 2,
            is_visible: true,
            props: {
              title: "Discover Japan with Confidence",
              subtitle: "Award-winning tours since 1998",
              backgroundImage: "https://cdn.example.com/images/hero-japan.jpg",
            },
          },
          {
            id: "block_003",
            type: "blockv3",
            sort_order: 2,
            is_visible: true,
            props: {
              title: "1111111111111111112222222222222222",
              subtitle: "Award-winning tours since 1998",
              backgroundImage: "https://cdn.example.com/images/hero-japan.jpg",
            },
          },
        ],
      },
    ],
  };
});
