/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AddCmsComponentInput } from './add-cms-component-input';
 /**
 * page增加输入参数
 *
 * @export
 * @interface AddCmsPageInput
 */
export interface AddCmsPageInput {

    /**
     * Pagetype
     *
     * @type {string}
     * @memberof AddCmsPageInput
     */
    pagetype: string;

    /**
     * @type {number}
     * @memberof AddCmsPageInput
     */
    pid?: number;

    /**
     * TemplateId
     *
     * @type {number}
     * @memberof AddCmsPageInput
     */
    templateId?: number | null;

    /**
     * Title
     *
     * @type {string}
     * @memberof AddCmsPageInput
     */
    title?: string | null;

    /**
     * SubTitle
     *
     * @type {string}
     * @memberof AddCmsPageInput
     */
    subTitle: string;

    /**
     * Status
     *
     * @type {number}
     * @memberof AddCmsPageInput
     */
    status: number;

    /**
     * RequestPath
     *
     * @type {string}
     * @memberof AddCmsPageInput
     */
    requestPath?: string | null;

    /**
     * RealPath
     *
     * @type {string}
     * @memberof AddCmsPageInput
     */
    realPath?: string | null;

    /**
     * IsDynamic
     *
     * @type {boolean}
     * @memberof AddCmsPageInput
     */
    isDynamic: boolean;

    /**
     * Description
     *
     * @type {string}
     * @memberof AddCmsPageInput
     */
    description?: string | null;

    /**
     * Keywords
     *
     * @type {string}
     * @memberof AddCmsPageInput
     */
    keywords?: string | null;

    /**
     * CanonicalUrl
     *
     * @type {string}
     * @memberof AddCmsPageInput
     */
    canonicalUrl?: string | null;

    /**
     * Robots
     *
     * @type {string}
     * @memberof AddCmsPageInput
     */
    robots?: string | null;

    /**
     * OgTitle
     *
     * @type {string}
     * @memberof AddCmsPageInput
     */
    ogTitle?: string | null;

    /**
     * OgImage
     *
     * @type {string}
     * @memberof AddCmsPageInput
     */
    ogImage?: string | null;

    /**
     * OgType
     *
     * @type {string}
     * @memberof AddCmsPageInput
     */
    ogType?: string | null;

    /**
     * DeleteTime
     *
     * @type {Date}
     * @memberof AddCmsPageInput
     */
    deleteTime?: Date | null;

    /**
     * @type {Array<AddCmsComponentInput>}
     * @memberof AddCmsPageInput
     */
    addCmsComponentInput?: Array<AddCmsComponentInput> | null;
}
