/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SysUser } from './sys-user';
 /**
 * 
 *
 * @export
 * @interface AddOpenAccessInput
 */
export interface AddOpenAccessInput {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof AddOpenAccessInput
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof AddOpenAccessInput
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof AddOpenAccessInput
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof AddOpenAccessInput
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof AddOpenAccessInput
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof AddOpenAccessInput
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof AddOpenAccessInput
     */
    updateUserName?: string | null;

    /**
     * 绑定租户Id
     *
     * @type {number}
     * @memberof AddOpenAccessInput
     */
    bindTenantId?: number;

    /**
     * @type {SysUser}
     * @memberof AddOpenAccessInput
     */
    bindUser?: SysUser;

    /**
     * 身份标识
     *
     * @type {string}
     * @memberof AddOpenAccessInput
     */
    accessKey: string;

    /**
     * 密钥
     *
     * @type {string}
     * @memberof AddOpenAccessInput
     */
    accessSecret: string;

    /**
     * 绑定用户Id
     *
     * @type {number}
     * @memberof AddOpenAccessInput
     */
    bindUserId: number;
}
