/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 增加文件存储提供者输入参数
 *
 * @export
 * @interface AddFileProviderInput
 */
export interface AddFileProviderInput {

    /**
     * 存储提供者
     *
     * @type {string}
     * @memberof AddFileProviderInput
     */
    provider: string;

    /**
     * 存储桶名称
     *
     * @type {string}
     * @memberof AddFileProviderInput
     */
    bucketName: string;

    /**
     * 访问密钥ID（所有云服务商统一使用此字段）
     *
     * @type {string}
     * @memberof AddFileProviderInput
     */
    accessKey?: string | null;

    /**
     * 密钥
     *
     * @type {string}
     * @memberof AddFileProviderInput
     */
    secretKey?: string | null;

    /**
     * 地域
     *
     * @type {string}
     * @memberof AddFileProviderInput
     */
    region?: string | null;

    /**
     * 端点地址
     *
     * @type {string}
     * @memberof AddFileProviderInput
     */
    endpoint?: string | null;

    /**
     * 是否启用HTTPS
     *
     * @type {boolean}
     * @memberof AddFileProviderInput
     */
    isEnableHttps?: boolean | null;

    /**
     * 是否启用缓存
     *
     * @type {boolean}
     * @memberof AddFileProviderInput
     */
    isEnableCache?: boolean | null;

    /**
     * 是否启用
     *
     * @type {boolean}
     * @memberof AddFileProviderInput
     */
    isEnable?: boolean | null;

    /**
     * 是否默认提供者
     *
     * @type {boolean}
     * @memberof AddFileProviderInput
     */
    isDefault?: boolean | null;

    /**
     * 自定义域名
     *
     * @type {string}
     * @memberof AddFileProviderInput
     */
    sinceDomain?: string | null;

    /**
     * 排序号
     *
     * @type {number}
     * @memberof AddFileProviderInput
     */
    orderNo?: number | null;

    /**
     * 备注
     *
     * @type {string}
     * @memberof AddFileProviderInput
     */
    remark?: string | null;

    /**
     * 支持的业务类型（JSON格式）
     *
     * @type {string}
     * @memberof AddFileProviderInput
     */
    businessTypes?: string | null;

    /**
     * 优先级
     *
     * @type {number}
     * @memberof AddFileProviderInput
     */
    priority?: number;
}
