/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * component add string的
 *
 * @export
 * @interface AddBatchCmsComponentInput
 */
export interface AddBatchCmsComponentInput {

    /**
     * @type {string}
     * @memberof AddBatchCmsComponentInput
     */
    id?: string | null;

    /**
     * PageId
     *
     * @type {string}
     * @memberof AddBatchCmsComponentInput
     */
    pid?: string | null;

    /**
     * ComponentTypeId
     *
     * @type {number}
     * @memberof AddBatchCmsComponentInput
     */
    componentTypeId: number;

    /**
     * Props
     *
     * @type {string}
     * @memberof AddBatchCmsComponentInput
     */
    props: string;

    /**
     * Styles
     *
     * @type {string}
     * @memberof AddBatchCmsComponentInput
     */
    styles?: string | null;

    /**
     * SortOrder
     *
     * @type {number}
     * @memberof AddBatchCmsComponentInput
     */
    sortOrder: number;

    /**
     * IsVisible
     *
     * @type {boolean}
     * @memberof AddBatchCmsComponentInput
     */
    isVisible: boolean;

    /**
     * DeleteTime
     *
     * @type {Date}
     * @memberof AddBatchCmsComponentInput
     */
    deleteTime?: Date | null;
}
