/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FinishStatusEnum } from './finish-status-enum';
 /**
 * 
 *
 * @export
 * @interface AddScheduleInput
 */
export interface AddScheduleInput {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof AddScheduleInput
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof AddScheduleInput
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof AddScheduleInput
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof AddScheduleInput
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof AddScheduleInput
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof AddScheduleInput
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof AddScheduleInput
     */
    updateUserName?: string | null;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof AddScheduleInput
     */
    tenantId?: number | null;

    /**
     * 用户Id
     *
     * @type {number}
     * @memberof AddScheduleInput
     */
    userId?: number;

    /**
     * 日程日期
     *
     * @type {Date}
     * @memberof AddScheduleInput
     */
    scheduleTime?: Date | null;

    /**
     * 开始时间
     *
     * @type {string}
     * @memberof AddScheduleInput
     */
    startTime?: string | null;

    /**
     * 结束时间
     *
     * @type {string}
     * @memberof AddScheduleInput
     */
    endTime?: string | null;

    /**
     * @type {FinishStatusEnum}
     * @memberof AddScheduleInput
     */
    status?: FinishStatusEnum;

    /**
     * 日程内容
     *
     * @type {string}
     * @memberof AddScheduleInput
     */
    content: string;
}
