/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { StatusEnum } from './status-enum';
import { SysOrg } from './sys-org';
 /**
 * 
 *
 * @export
 * @interface AddOrgInput
 */
export interface AddOrgInput {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof AddOrgInput
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof AddOrgInput
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof AddOrgInput
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof AddOrgInput
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof AddOrgInput
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof AddOrgInput
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof AddOrgInput
     */
    updateUserName?: string | null;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof AddOrgInput
     */
    tenantId?: number | null;

    /**
     * 父Id
     *
     * @type {number}
     * @memberof AddOrgInput
     */
    pid?: number;

    /**
     * 编码
     *
     * @type {string}
     * @memberof AddOrgInput
     */
    code?: string | null;

    /**
     * 级别
     *
     * @type {number}
     * @memberof AddOrgInput
     */
    level?: number | null;

    /**
     * 负责人Id
     *
     * @type {number}
     * @memberof AddOrgInput
     */
    directorId?: number | null;

    /**
     * 排序
     *
     * @type {number}
     * @memberof AddOrgInput
     */
    orderNo?: number;

    /**
     * @type {StatusEnum}
     * @memberof AddOrgInput
     */
    status?: StatusEnum;

    /**
     * 备注
     *
     * @type {string}
     * @memberof AddOrgInput
     */
    remark?: string | null;

    /**
     * 机构子项
     *
     * @type {Array<SysOrg>}
     * @memberof AddOrgInput
     */
    children?: Array<SysOrg> | null;

    /**
     * 是否禁止选中
     *
     * @type {boolean}
     * @memberof AddOrgInput
     */
    disabled?: boolean;

    /**
     * 名称
     *
     * @type {string}
     * @memberof AddOrgInput
     */
    name: string;

    /**
     * 机构类型
     *
     * @type {string}
     * @memberof AddOrgInput
     */
    type?: string | null;
}
