/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 翻译表增加输入参数
 *
 * @export
 * @interface AddSysLangTextInput
 */
export interface AddSysLangTextInput {

    /**
     * 所属实体名
     *
     * @type {string}
     * @memberof AddSysLangTextInput
     */
    entityName: string;

    /**
     * 所属实体ID
     *
     * @type {number}
     * @memberof AddSysLangTextInput
     */
    entityId: number;

    /**
     * 字段名
     *
     * @type {string}
     * @memberof AddSysLangTextInput
     */
    fieldName: string;

    /**
     * 语言代码
     *
     * @type {string}
     * @memberof AddSysLangTextInput
     */
    langCode: string;

    /**
     * 翻译内容
     *
     * @type {string}
     * @memberof AddSysLangTextInput
     */
    content: string;
}
