/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ComponentKindEnum } from './component-kind-enum';
 /**
 * component_type增加输入参数
 *
 * @export
 * @interface AddCmsComponentTypeInput
 */
export interface AddCmsComponentTypeInput {

    /**
     * Name
     *
     * @type {string}
     * @memberof AddCmsComponentTypeInput
     */
    name: string;

    /**
     * @type {ComponentKindEnum}
     * @memberof AddCmsComponentTypeInput
     */
    componentKind: ComponentKindEnum;

    /**
     * Description
     *
     * @type {string}
     * @memberof AddCmsComponentTypeInput
     */
    description?: string | null;

    /**
     * DefaultProps
     *
     * @type {string}
     * @memberof AddCmsComponentTypeInput
     */
    defaultProps?: string | null;

    /**
     * SetStyles
     *
     * @type {string}
     * @memberof AddCmsComponentTypeInput
     */
    setStyles?: string | null;

    /**
     * Fields
     *
     * @type {string}
     * @memberof AddCmsComponentTypeInput
     */
    fields?: string | null;

    /**
     * Status
     *
     * @type {number}
     * @memberof AddCmsComponentTypeInput
     */
    status: number;

    /**
     * DeleteTime
     *
     * @type {Date}
     * @memberof AddCmsComponentTypeInput
     */
    deleteTime?: Date | null;
}
