/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 基础存储过程输入类
 *
 * @export
 * @interface BaseProcInput
 */
export interface BaseProcInput {

    /**
     * ProcId
     *
     * @type {string}
     * @memberof BaseProcInput
     */
    procId?: string | null;

    /**
     * 数据库配置Id
     *
     * @type {string}
     * @memberof BaseProcInput
     */
    configId?: string | null;

    /**
     * 存储过程输入参数
     *
     * @type {{ [key: string]: any; }}
     * @memberof BaseProcInput
     * @example {"id":"351060822794565"}
     */
    procParams?: { [key: string]: any; } | null;
}
