/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * CMS page component instance
 *
 * @export
 * @interface CmsComponent
 */
export interface CmsComponent {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof CmsComponent
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof CmsComponent
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof CmsComponent
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof CmsComponent
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof CmsComponent
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof CmsComponent
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof CmsComponent
     */
    updateUserName?: string | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof CmsComponent
     */
    isDelete?: boolean;

    /**
     * 软删除时间
     *
     * @type {Date}
     * @memberof CmsComponent
     */
    deleteTime?: Date | null;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof CmsComponent
     */
    tenantId?: number | null;

    /**
     * Associated page ID
     *
     * @type {number}
     * @memberof CmsComponent
     */
    pageId?: number;

    /**
     * Component code
     *
     * @type {number}
     * @memberof CmsComponent
     */
    componentTypeId?: number;

    /**
     * Pid
     *
     * @type {number}
     * @memberof CmsComponent
     */
    pid?: number;

    /**
     * Sort order
     *
     * @type {string}
     * @memberof CmsComponent
     */
    props?: string | null;

    /**
     * JSON schema
     *
     * @type {string}
     * @memberof CmsComponent
     */
    styles?: string | null;

    /**
     * Sort order
     *
     * @type {number}
     * @memberof CmsComponent
     */
    sortOrder?: number;

    /**
     * Whether component is visible
     *
     * @type {boolean}
     * @memberof CmsComponent
     */
    isVisible?: boolean;
}
