/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ComponentKindEnum } from './component-kind-enum';
 /**
 * CMS component type definition/management
 *
 * @export
 * @interface CmsComponentType
 */
export interface CmsComponentType {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof CmsComponentType
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof CmsComponentType
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof CmsComponentType
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof CmsComponentType
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof CmsComponentType
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof CmsComponentType
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof CmsComponentType
     */
    updateUserName?: string | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof CmsComponentType
     */
    isDelete?: boolean;

    /**
     * 软删除时间
     *
     * @type {Date}
     * @memberof CmsComponentType
     */
    deleteTime?: Date | null;

    /**
     * Component name
     *
     * @type {string}
     * @memberof CmsComponentType
     */
    name?: string | null;

    /**
     * @type {ComponentKindEnum}
     * @memberof CmsComponentType
     */
    componentKind?: ComponentKindEnum;

    /**
     * Description
     *
     * @type {string}
     * @memberof CmsComponentType
     */
    description?: string | null;

    /**
     * Default properties (JSON)
     *
     * @type {string}
     * @memberof CmsComponentType
     */
    defaultProps?: string | null;

    /**
     * JSON schema
     *
     * @type {string}
     * @memberof CmsComponentType
     */
    setStyles?: string | null;

    /**
     * JSON schema
     *
     * @type {string}
     * @memberof CmsComponentType
     */
    fields?: string | null;

    /**
     * Status 10,20,30
     *
     * @type {number}
     * @memberof CmsComponentType
     */
    status?: number;

    /**
     * IsRemote
     *
     * @type {boolean}
     * @memberof CmsComponentType
     */
    isRemote?: boolean;
}
