/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * component输出参数
 *
 * @export
 * @interface CmsComponentOutput
 */
export interface CmsComponentOutput {

    /**
     * 主键Id
     *
     * @type {number}
     * @memberof CmsComponentOutput
     */
    id?: number;

    /**
     * PageId
     *
     * @type {number}
     * @memberof CmsComponentOutput
     */
    pageId?: number;

    /**
     * ComponentTypeId
     *
     * @type {number}
     * @memberof CmsComponentOutput
     */
    componentTypeId?: number;

    /**
     * Pid
     *
     * @type {number}
     * @memberof CmsComponentOutput
     */
    pid?: number;

    /**
     * Props
     *
     * @type {string}
     * @memberof CmsComponentOutput
     */
    props?: string | null;

    /**
     * Styles
     *
     * @type {string}
     * @memberof CmsComponentOutput
     */
    styles?: string | null;

    /**
     * SortOrder
     *
     * @type {number}
     * @memberof CmsComponentOutput
     */
    sortOrder?: number;

    /**
     * IsVisible
     *
     * @type {boolean}
     * @memberof CmsComponentOutput
     */
    isVisible?: boolean;

    /**
     * TenantId
     *
     * @type {number}
     * @memberof CmsComponentOutput
     */
    tenantId?: number | null;

    /**
     * IsDelete
     *
     * @type {boolean}
     * @memberof CmsComponentOutput
     */
    isDelete?: boolean;

    /**
     * DeleteTime
     *
     * @type {Date}
     * @memberof CmsComponentOutput
     */
    deleteTime?: Date | null;

    /**
     * CreateTime
     *
     * @type {Date}
     * @memberof CmsComponentOutput
     */
    createTime?: Date | null;

    /**
     * UpdateTime
     *
     * @type {Date}
     * @memberof CmsComponentOutput
     */
    updateTime?: Date | null;

    /**
     * CreateUserId
     *
     * @type {number}
     * @memberof CmsComponentOutput
     */
    createUserId?: number | null;

    /**
     * CreateUserName
     *
     * @type {string}
     * @memberof CmsComponentOutput
     */
    createUserName?: string | null;

    /**
     * UpdateUserId
     *
     * @type {number}
     * @memberof CmsComponentOutput
     */
    updateUserId?: number | null;

    /**
     * UpdateUserName
     *
     * @type {string}
     * @memberof CmsComponentOutput
     */
    updateUserName?: string | null;
}
