/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ComponentKindEnum } from './component-kind-enum';
 /**
 * component_type输出参数
 *
 * @export
 * @interface CmsComponentTypeDto
 */
export interface CmsComponentTypeDto {

    /**
     * 主键Id
     *
     * @type {number}
     * @memberof CmsComponentTypeDto
     */
    id?: number;

    /**
     * Name
     *
     * @type {string}
     * @memberof CmsComponentTypeDto
     */
    name?: string | null;

    /**
     * @type {ComponentKindEnum}
     * @memberof CmsComponentTypeDto
     */
    componentKind?: ComponentKindEnum;

    /**
     * Description
     *
     * @type {string}
     * @memberof CmsComponentTypeDto
     */
    description?: string | null;

    /**
     * DefaultProps
     *
     * @type {string}
     * @memberof CmsComponentTypeDto
     */
    defaultProps?: string | null;

    /**
     * SetStyles
     *
     * @type {string}
     * @memberof CmsComponentTypeDto
     */
    setStyles?: string | null;

    /**
     * Fields
     *
     * @type {string}
     * @memberof CmsComponentTypeDto
     */
    fields?: string | null;

    /**
     * Status
     *
     * @type {number}
     * @memberof CmsComponentTypeDto
     */
    status?: number;

    /**
     * IsDelete
     *
     * @type {boolean}
     * @memberof CmsComponentTypeDto
     */
    isDelete?: boolean;

    /**
     * DeleteTime
     *
     * @type {Date}
     * @memberof CmsComponentTypeDto
     */
    deleteTime?: Date | null;

    /**
     * CreateTime
     *
     * @type {Date}
     * @memberof CmsComponentTypeDto
     */
    createTime?: Date | null;

    /**
     * UpdateTime
     *
     * @type {Date}
     * @memberof CmsComponentTypeDto
     */
    updateTime?: Date | null;

    /**
     * CreateUserId
     *
     * @type {number}
     * @memberof CmsComponentTypeDto
     */
    createUserId?: number | null;

    /**
     * CreateUserName
     *
     * @type {string}
     * @memberof CmsComponentTypeDto
     */
    createUserName?: string | null;

    /**
     * UpdateUserId
     *
     * @type {number}
     * @memberof CmsComponentTypeDto
     */
    updateUserId?: number | null;

    /**
     * UpdateUserName
     *
     * @type {string}
     * @memberof CmsComponentTypeDto
     */
    updateUserName?: string | null;
}
