/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * cmscontentdata输出参数
 *
 * @export
 * @interface CmsComponentDataOutput
 */
export interface CmsComponentDataOutput {

    /**
     * 主键Id
     *
     * @type {number}
     * @memberof CmsComponentDataOutput
     */
    id?: number;

    /**
     * @type {number}
     * @memberof CmsComponentDataOutput
     */
    cmsComponentId?: number;

    /**
     * @type {string}
     * @memberof CmsComponentDataOutput
     */
    title?: string | null;

    /**
     * @type {string}
     * @memberof CmsComponentDataOutput
     */
    subtitle?: string | null;

    /**
     * @type {string}
     * @memberof CmsComponentDataOutput
     */
    content?: string | null;

    /**
     * @type {string}
     * @memberof CmsComponentDataOutput
     */
    icon?: string | null;

    /**
     * @type {string}
     * @memberof CmsComponentDataOutput
     */
    props?: string | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof CmsComponentDataOutput
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof CmsComponentDataOutput
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof CmsComponentDataOutput
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof CmsComponentDataOutput
     */
    updateUserName?: string | null;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof CmsComponentDataOutput
     */
    createTime?: Date | null;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof CmsComponentDataOutput
     */
    updateTime?: Date | null;

    /**
     * @type {string}
     * @memberof CmsComponentDataOutput
     */
    linkUrl?: string | null;

    /**
     * @type {string}
     * @memberof CmsComponentDataOutput
     */
    imageUrl?: string | null;

    /**
     * @type {string}
     * @memberof CmsComponentDataOutput
     */
    bgColor?: string | null;
}
