/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * CMS Page（N Page + Tempalte page）
 *
 * @export
 * @interface CmsPage
 */
export interface CmsPage {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof CmsPage
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof CmsPage
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof CmsPage
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof CmsPage
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof CmsPage
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof CmsPage
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof CmsPage
     */
    updateUserName?: string | null;

    /**
     * 软删除
     *
     * @type {boolean}
     * @memberof CmsPage
     */
    isDelete?: boolean;

    /**
     * 软删除时间
     *
     * @type {Date}
     * @memberof CmsPage
     */
    deleteTime?: Date | null;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof CmsPage
     */
    tenantId?: number | null;

    /**
     * Page type: \"template\" or \"page\"
     *
     * @type {string}
     * @memberof CmsPage
     */
    pagetype?: string | null;

    /**
     * @type {number}
     * @memberof CmsPage
     */
    templateId?: number;

    /**
     * @type {number}
     * @memberof CmsPage
     */
    pid?: number | null;

    /**
     * SEO title
     *
     * @type {string}
     * @memberof CmsPage
     */
    title?: string | null;

    /**
     * SubeTitle
     *
     * @type {string}
     * @memberof CmsPage
     */
    subTitle?: string | null;

    /**
     * Status
     *
     * @type {number}
     * @memberof CmsPage
     */
    status?: number;

    /**
     * Request path
     *
     * @type {string}
     * @memberof CmsPage
     */
    requestPath?: string | null;

    /**
     * Real path
     *
     * @type {string}
     * @memberof CmsPage
     */
    realPath?: string | null;

    /**
     * Whether the page is dynamic
     *
     * @type {boolean}
     * @memberof CmsPage
     */
    isDynamic?: boolean;

    /**
     * SEO description
     *
     * @type {string}
     * @memberof CmsPage
     */
    description?: string | null;

    /**
     * Keywords
     *
     * @type {string}
     * @memberof CmsPage
     */
    keywords?: string | null;

    /**
     * Canonical URL
     *
     * @type {string}
     * @memberof CmsPage
     */
    canonicalUrl?: string | null;

    /**
     * Robots setting
     *
     * @type {string}
     * @memberof CmsPage
     */
    robots?: string | null;

    /**
     * Open Graph title
     *
     * @type {string}
     * @memberof CmsPage
     */
    ogTitle?: string | null;

    /**
     * Open Graph image URL
     *
     * @type {string}
     * @memberof CmsPage
     */
    ogImage?: string | null;

    /**
     * Open Graph type
     *
     * @type {string}
     * @memberof CmsPage
     */
    ogType?: string | null;
}
