/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * CMS page component data
 *
 * @export
 * @interface CmsComponentData
 */
export interface CmsComponentData {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof CmsComponentData
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof CmsComponentData
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof CmsComponentData
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof CmsComponentData
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof CmsComponentData
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof CmsComponentData
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof CmsComponentData
     */
    updateUserName?: string | null;

    /**
     * Component instance ID
     *
     * @type {number}
     * @memberof CmsComponentData
     */
    cmsComponentId?: number;

    /**
     * Title
     *
     * @type {string}
     * @memberof CmsComponentData
     */
    title?: string | null;

    /**
     * Subtitle
     *
     * @type {string}
     * @memberof CmsComponentData
     */
    subtitle?: string | null;

    /**
     * Content
     *
     * @type {string}
     * @memberof CmsComponentData
     */
    content?: string | null;

    /**
     * Link URL
     *
     * @type {string}
     * @memberof CmsComponentData
     */
    linkUrl?: string | null;

    /**
     * Image URL
     *
     * @type {string}
     * @memberof CmsComponentData
     */
    imageUrl?: string | null;

    /**
     * Background color
     *
     * @type {string}
     * @memberof CmsComponentData
     */
    bgColor?: string | null;

    /**
     * Icon
     *
     * @type {string}
     * @memberof CmsComponentData
     */
    icon?: string | null;

    /**
     * Custom properties (JSON)
     *
     * @type {string}
     * @memberof CmsComponentData
     */
    props?: string | null;
}
