/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * page输出参数
 *
 * @export
 * @interface CmsPageOutput
 */
export interface CmsPageOutput {

    /**
     * 主键Id
     *
     * @type {number}
     * @memberof CmsPageOutput
     */
    id?: number;

    /**
     * Pagetype
     *
     * @type {string}
     * @memberof CmsPageOutput
     */
    pagetype?: string | null;

    /**
     * @type {number}
     * @memberof CmsPageOutput
     */
    pid?: number;

    /**
     * TemplateId
     *
     * @type {number}
     * @memberof CmsPageOutput
     */
    templateId?: number;

    /**
     * Title
     *
     * @type {string}
     * @memberof CmsPageOutput
     */
    title?: string | null;

    /**
     * SubTitle
     *
     * @type {string}
     * @memberof CmsPageOutput
     */
    subTitle?: string | null;

    /**
     * Status
     *
     * @type {number}
     * @memberof CmsPageOutput
     */
    status?: number;

    /**
     * RequestPath
     *
     * @type {string}
     * @memberof CmsPageOutput
     */
    requestPath?: string | null;

    /**
     * RealPath
     *
     * @type {string}
     * @memberof CmsPageOutput
     */
    realPath?: string | null;

    /**
     * IsDynamic
     *
     * @type {boolean}
     * @memberof CmsPageOutput
     */
    isDynamic?: boolean;

    /**
     * Description
     *
     * @type {string}
     * @memberof CmsPageOutput
     */
    description?: string | null;

    /**
     * Keywords
     *
     * @type {string}
     * @memberof CmsPageOutput
     */
    keywords?: string | null;

    /**
     * CanonicalUrl
     *
     * @type {string}
     * @memberof CmsPageOutput
     */
    canonicalUrl?: string | null;

    /**
     * Robots
     *
     * @type {string}
     * @memberof CmsPageOutput
     */
    robots?: string | null;

    /**
     * OgTitle
     *
     * @type {string}
     * @memberof CmsPageOutput
     */
    ogTitle?: string | null;

    /**
     * OgImage
     *
     * @type {string}
     * @memberof CmsPageOutput
     */
    ogImage?: string | null;

    /**
     * OgType
     *
     * @type {string}
     * @memberof CmsPageOutput
     */
    ogType?: string | null;

    /**
     * TenantId
     *
     * @type {number}
     * @memberof CmsPageOutput
     */
    tenantId?: number | null;

    /**
     * IsDelete
     *
     * @type {boolean}
     * @memberof CmsPageOutput
     */
    isDelete?: boolean;

    /**
     * DeleteTime
     *
     * @type {Date}
     * @memberof CmsPageOutput
     */
    deleteTime?: Date | null;

    /**
     * CreateTime
     *
     * @type {Date}
     * @memberof CmsPageOutput
     */
    createTime?: Date | null;

    /**
     * UpdateTime
     *
     * @type {Date}
     * @memberof CmsPageOutput
     */
    updateTime?: Date | null;

    /**
     * CreateUserId
     *
     * @type {number}
     * @memberof CmsPageOutput
     */
    createUserId?: number | null;

    /**
     * CreateUserName
     *
     * @type {string}
     * @memberof CmsPageOutput
     */
    createUserName?: string | null;

    /**
     * UpdateUserId
     *
     * @type {number}
     * @memberof CmsPageOutput
     */
    updateUserId?: number | null;

    /**
     * UpdateUserName
     *
     * @type {string}
     * @memberof CmsPageOutput
     */
    updateUserName?: string | null;
}
