/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * <br />&nbsp;Container Container = 10<br />&nbsp;Layout Layout = 20<br />&nbsp;Content Content = 30<br />
 * @export
 * @enum {string}
 */
export enum ComponentKindEnum {
    NUMBER_10 = 10,
    NUMBER_20 = 20,
    NUMBER_30 = 30
}

