/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ConstOutput
 */
export interface ConstOutput {

    /**
     * 名称
     *
     * @type {string}
     * @memberof ConstOutput
     */
    name?: string | null;

    /**
     * 编码
     *
     * @type {any}
     * @memberof ConstOutput
     */
    code?: any | null;

    /**
     * 扩展字段
     *
     * @type {any}
     * @memberof ConstOutput
     */
    data?: any | null;
}
