/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateEntityInput
 */
export interface CreateEntityInput {

    /**
     * 表名
     *
     * @type {string}
     * @memberof CreateEntityInput
     * @example student
     */
    tableName?: string | null;

    /**
     * 实体名
     *
     * @type {string}
     * @memberof CreateEntityInput
     * @example Student
     */
    entityName?: string | null;

    /**
     * 基类名
     *
     * @type {string}
     * @memberof CreateEntityInput
     * @example AutoIncrementEntity
     */
    baseClassName?: string | null;

    /**
     * 导出位置
     *
     * @type {string}
     * @memberof CreateEntityInput
     * @example Web.Application
     */
    position?: string | null;

    /**
     * 库标识
     *
     * @type {string}
     * @memberof CreateEntityInput
     */
    configId?: string | null;
}
