/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ExtUserInfo
 */
export interface ExtUserInfo {

    /**
     * @type {string}
     * @memberof ExtUserInfo
     */
    certNo?: string | null;

    /**
     * @type {string}
     * @memberof ExtUserInfo
     */
    certType?: string | null;

    /**
     * @type {string}
     * @memberof ExtUserInfo
     */
    fixBuyer?: string | null;

    /**
     * @type {string}
     * @memberof ExtUserInfo
     */
    identityHash?: string | null;

    /**
     * @type {string}
     * @memberof ExtUserInfo
     */
    minAge?: string | null;

    /**
     * @type {string}
     * @memberof ExtUserInfo
     */
    mobile?: string | null;

    /**
     * @type {string}
     * @memberof ExtUserInfo
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof ExtUserInfo
     */
    needCheckInfo?: string | null;
}
