/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ExtendParams
 */
export interface ExtendParams {

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    cardType?: string | null;

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    creditExtInfo?: string | null;

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    hbFqNum?: string | null;

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    hbFqSellerPercent?: string | null;

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    industryRefluxInfo?: string | null;

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    royaltyFreeze?: string | null;

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    specifiedSellerName?: string | null;

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    sysServiceProviderId?: string | null;

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    tcInstallmentOrderId?: string | null;

    /**
     * @type {string}
     * @memberof ExtendParams
     */
    tradeComponentOrderId?: string | null;
}
