/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { HttpMethodEnum } from './http-method-enum';
 /**
 * 
 *
 * @export
 * @interface GenerateSignatureInput
 */
export interface GenerateSignatureInput {

    /**
     * 身份标识
     *
     * @type {string}
     * @memberof GenerateSignatureInput
     */
    accessKey: string;

    /**
     * 密钥
     *
     * @type {string}
     * @memberof GenerateSignatureInput
     */
    accessSecret: string;

    /**
     * @type {HttpMethodEnum}
     * @memberof GenerateSignatureInput
     */
    method?: HttpMethodEnum;

    /**
     * 请求接口地址
     *
     * @type {string}
     * @memberof GenerateSignatureInput
     */
    url: string;

    /**
     * 时间戳
     *
     * @type {number}
     * @memberof GenerateSignatureInput
     */
    timestamp: number;

    /**
     * 随机数
     *
     * @type {string}
     * @memberof GenerateSignatureInput
     */
    nonce: string;
}
