/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface LogVisOutput
 */
export interface LogVisOutput {

    /**
     * 登录地点
     *
     * @type {string}
     * @memberof LogVisOutput
     */
    location?: string | null;

    /**
     * 经度
     *
     * @type {number}
     * @memberof LogVisOutput
     */
    longitude?: number | null;

    /**
     * 维度
     *
     * @type {number}
     * @memberof LogVisOutput
     */
    latitude?: number | null;

    /**
     * 真实姓名
     *
     * @type {string}
     * @memberof LogVisOutput
     */
    realName?: string | null;

    /**
     * 日志时间
     *
     * @type {Date}
     * @memberof LogVisOutput
     */
    logDateTime?: Date | null;
}
