/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 用户登录参数
 *
 * @export
 * @interface LoginInput
 */
export interface LoginInput {

    /**
     * 账号
     *
     * @type {string}
     * @memberof LoginInput
     * @example admin
     */
    account: string;

    /**
     * 密码
     *
     * @type {string}
     * @memberof LoginInput
     * @example 123456
     */
    password: string;

    /**
     * 租户
     *
     * @type {number}
     * @memberof LoginInput
     */
    tenantId?: number | null;

    /**
     * 验证码Id
     *
     * @type {number}
     * @memberof LoginInput
     */
    codeId?: number;

    /**
     * 验证码
     *
     * @type {string}
     * @memberof LoginInput
     */
    code?: string | null;
}
