/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 用户登录结果
 *
 * @export
 * @interface LoginOutput
 */
export interface LoginOutput {

    /**
     * 令牌Token
     *
     * @type {string}
     * @memberof LoginOutput
     */
    accessToken?: string | null;

    /**
     * 刷新Token
     *
     * @type {string}
     * @memberof LoginOutput
     */
    refreshToken?: string | null;

    /**
     * 个性化首页
     *
     * @type {string}
     * @memberof LoginOutput
     */
    homepage?: string | null;
}
