/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OrgTreeOutput } from './org-tree-output';
 /**
 * 机构树形输出
 *
 * @export
 * @interface OrgTreeOutput
 */
export interface OrgTreeOutput {

    /**
     * 主键Id
     *
     * @type {number}
     * @memberof OrgTreeOutput
     */
    id?: number;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof OrgTreeOutput
     */
    tenantId?: number;

    /**
     * 父Id
     *
     * @type {number}
     * @memberof OrgTreeOutput
     */
    pid?: number;

    /**
     * 名称
     *
     * @type {string}
     * @memberof OrgTreeOutput
     */
    name?: string | null;

    /**
     * 机构子项
     *
     * @type {Array<OrgTreeOutput>}
     * @memberof OrgTreeOutput
     */
    children?: Array<OrgTreeOutput> | null;

    /**
     * 是否禁止选中
     *
     * @type {boolean}
     * @memberof OrgTreeOutput
     */
    disabled?: boolean;
}
