/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Filter } from './filter';
import { Search } from './search';
 /**
 * component分页查询输入参数
 *
 * @export
 * @interface PageCmsComponentInput
 */
export interface PageCmsComponentInput {

    /**
     * @type {Search}
     * @memberof PageCmsComponentInput
     */
    search?: Search;

    /**
     * 模糊查询关键字
     *
     * @type {string}
     * @memberof PageCmsComponentInput
     */
    keyword?: string | null;

    /**
     * @type {Filter}
     * @memberof PageCmsComponentInput
     */
    filter?: Filter;

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof PageCmsComponentInput
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof PageCmsComponentInput
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof PageCmsComponentInput
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof PageCmsComponentInput
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof PageCmsComponentInput
     */
    descStr?: string | null;

    /**
     * PageId
     *
     * @type {number}
     * @memberof PageCmsComponentInput
     */
    pageId?: number | null;

    /**
     * ComponentTypeId
     *
     * @type {number}
     * @memberof PageCmsComponentInput
     */
    componentTypeId?: number | null;

    /**
     * Pid
     *
     * @type {number}
     * @memberof PageCmsComponentInput
     */
    pid?: number | null;

    /**
     * Props
     *
     * @type {string}
     * @memberof PageCmsComponentInput
     */
    props?: string | null;

    /**
     * Styles
     *
     * @type {string}
     * @memberof PageCmsComponentInput
     */
    styles?: string | null;

    /**
     * SortOrder
     *
     * @type {number}
     * @memberof PageCmsComponentInput
     */
    sortOrder?: number | null;

    /**
     * IsVisible
     *
     * @type {boolean}
     * @memberof PageCmsComponentInput
     */
    isVisible?: boolean | null;

    /**
     * DeleteTime范围
     *
     * @type {Array<Date>}
     * @memberof PageCmsComponentInput
     */
    deleteTimeRange?: Array<Date> | null;

    /**
     * 选中主键列表
     *
     * @type {Array<number>}
     * @memberof PageCmsComponentInput
     */
    selectKeyList?: Array<number> | null;
}
