/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ComponentKindEnum } from './component-kind-enum';
import { Filter } from './filter';
import { Search } from './search';
 /**
 * component_type分页查询输入参数
 *
 * @export
 * @interface PageCmsComponentTypeInput
 */
export interface PageCmsComponentTypeInput {

    /**
     * @type {Search}
     * @memberof PageCmsComponentTypeInput
     */
    search?: Search;

    /**
     * 模糊查询关键字
     *
     * @type {string}
     * @memberof PageCmsComponentTypeInput
     */
    keyword?: string | null;

    /**
     * @type {Filter}
     * @memberof PageCmsComponentTypeInput
     */
    filter?: Filter;

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof PageCmsComponentTypeInput
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof PageCmsComponentTypeInput
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof PageCmsComponentTypeInput
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof PageCmsComponentTypeInput
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof PageCmsComponentTypeInput
     */
    descStr?: string | null;

    /**
     * Name
     *
     * @type {string}
     * @memberof PageCmsComponentTypeInput
     */
    name?: string | null;

    /**
     * @type {ComponentKindEnum}
     * @memberof PageCmsComponentTypeInput
     */
    componentKind?: ComponentKindEnum;

    /**
     * Description
     *
     * @type {string}
     * @memberof PageCmsComponentTypeInput
     */
    description?: string | null;

    /**
     * DefaultProps
     *
     * @type {string}
     * @memberof PageCmsComponentTypeInput
     */
    defaultProps?: string | null;

    /**
     * SetStyles
     *
     * @type {string}
     * @memberof PageCmsComponentTypeInput
     */
    setStyles?: string | null;

    /**
     * Fields
     *
     * @type {string}
     * @memberof PageCmsComponentTypeInput
     */
    fields?: string | null;

    /**
     * Status
     *
     * @type {number}
     * @memberof PageCmsComponentTypeInput
     */
    status?: number | null;

    /**
     * DeleteTime范围
     *
     * @type {Array<Date>}
     * @memberof PageCmsComponentTypeInput
     */
    deleteTimeRange?: Array<Date> | null;

    /**
     * 选中主键列表
     *
     * @type {Array<number>}
     * @memberof PageCmsComponentTypeInput
     */
    selectKeyList?: Array<number> | null;
}
