/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Filter } from './filter';
import { Search } from './search';
 /**
 * page分页查询输入参数
 *
 * @export
 * @interface PageCmsPageInput
 */
export interface PageCmsPageInput {

    /**
     * @type {Search}
     * @memberof PageCmsPageInput
     */
    search?: Search;

    /**
     * 模糊查询关键字
     *
     * @type {string}
     * @memberof PageCmsPageInput
     */
    keyword?: string | null;

    /**
     * @type {Filter}
     * @memberof PageCmsPageInput
     */
    filter?: Filter;

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof PageCmsPageInput
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof PageCmsPageInput
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof PageCmsPageInput
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof PageCmsPageInput
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof PageCmsPageInput
     */
    descStr?: string | null;

    /**
     * Pagetype
     *
     * @type {string}
     * @memberof PageCmsPageInput
     */
    pagetype?: string | null;

    /**
     * TemplateId
     *
     * @type {number}
     * @memberof PageCmsPageInput
     */
    templateId?: number | null;

    /**
     * Title
     *
     * @type {string}
     * @memberof PageCmsPageInput
     */
    title?: string | null;

    /**
     * SubTitle
     *
     * @type {string}
     * @memberof PageCmsPageInput
     */
    subTitle?: string | null;

    /**
     * Status
     *
     * @type {number}
     * @memberof PageCmsPageInput
     */
    status?: number | null;

    /**
     * RequestPath
     *
     * @type {string}
     * @memberof PageCmsPageInput
     */
    requestPath?: string | null;

    /**
     * RealPath
     *
     * @type {string}
     * @memberof PageCmsPageInput
     */
    realPath?: string | null;

    /**
     * IsDynamic
     *
     * @type {boolean}
     * @memberof PageCmsPageInput
     */
    isDynamic?: boolean | null;

    /**
     * Description
     *
     * @type {string}
     * @memberof PageCmsPageInput
     */
    description?: string | null;

    /**
     * Keywords
     *
     * @type {string}
     * @memberof PageCmsPageInput
     */
    keywords?: string | null;

    /**
     * CanonicalUrl
     *
     * @type {string}
     * @memberof PageCmsPageInput
     */
    canonicalUrl?: string | null;

    /**
     * Robots
     *
     * @type {string}
     * @memberof PageCmsPageInput
     */
    robots?: string | null;

    /**
     * OgTitle
     *
     * @type {string}
     * @memberof PageCmsPageInput
     */
    ogTitle?: string | null;

    /**
     * OgImage
     *
     * @type {string}
     * @memberof PageCmsPageInput
     */
    ogImage?: string | null;

    /**
     * OgType
     *
     * @type {string}
     * @memberof PageCmsPageInput
     */
    ogType?: string | null;

    /**
     * DeleteTime范围
     *
     * @type {Array<Date>}
     * @memberof PageCmsPageInput
     */
    deleteTimeRange?: Array<Date> | null;

    /**
     * 选中主键列表
     *
     * @type {Array<number>}
     * @memberof PageCmsPageInput
     */
    selectKeyList?: Array<number> | null;
}
