/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 授权角色机构
 *
 * @export
 * @interface RoleOrgInput
 */
export interface RoleOrgInput {

    /**
     * 主键Id
     *
     * @type {number}
     * @memberof RoleOrgInput
     */
    id: number;

    /**
     * 数据范围
     *
     * @type {number}
     * @memberof RoleOrgInput
     */
    dataScope?: number;

    /**
     * 机构Id集合
     *
     * @type {Array<number>}
     * @memberof RoleOrgInput
     */
    orgIdList?: Array<number> | null;
}
