/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CmsComponentDataOutput } from './cms-component-data-output';
 /**
 * 分页泛型集合
 *
 * @export
 * @interface SqlSugarPagedListCmsComponentDataOutput
 */
export interface SqlSugarPagedListCmsComponentDataOutput {

    /**
     * 页码
     *
     * @type {number}
     * @memberof SqlSugarPagedListCmsComponentDataOutput
     */
    page?: number;

    /**
     * 页容量
     *
     * @type {number}
     * @memberof SqlSugarPagedListCmsComponentDataOutput
     */
    pageSize?: number;

    /**
     * 总条数
     *
     * @type {number}
     * @memberof SqlSugarPagedListCmsComponentDataOutput
     */
    total?: number;

    /**
     * 总页数
     *
     * @type {number}
     * @memberof SqlSugarPagedListCmsComponentDataOutput
     */
    totalPages?: number;

    /**
     * 当前页集合
     *
     * @type {Array<CmsComponentDataOutput>}
     * @memberof SqlSugarPagedListCmsComponentDataOutput
     */
    items?: Array<CmsComponentDataOutput> | null;

    /**
     * 是否有上一页
     *
     * @type {boolean}
     * @memberof SqlSugarPagedListCmsComponentDataOutput
     */
    hasPrevPage?: boolean;

    /**
     * 是否有下一页
     *
     * @type {boolean}
     * @memberof SqlSugarPagedListCmsComponentDataOutput
     */
    hasNextPage?: boolean;
}
