/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { KeyValuePairStringString } from './key-value-pair-string-string';
 /**
 * 接口压测输入参数
 *
 * @export
 * @interface StressTestInput
 */
export interface StressTestInput {

    /**
     * 接口请求地址
     *
     * @type {string}
     * @memberof StressTestInput
     * @example https://gitee.com/zuohuaijun/Admin.NET
     */
    requestUri: string;

    /**
     * 请求方式
     *
     * @type {string}
     * @memberof StressTestInput
     */
    requestMethod: string;

    /**
     * 每轮请求量
     *
     * @type {number}
     * @memberof StressTestInput
     * @example 100
     */
    numberOfRequests: number;

    /**
     * 压测轮数
     *
     * @type {number}
     * @memberof StressTestInput
     * @example 5
     */
    numberOfRounds: number;

    /**
     * 最大并行量（默认为当前主机逻辑处理器的数量）
     *
     * @type {number}
     * @memberof StressTestInput
     * @example 500
     */
    maxDegreeOfParallelism?: number | null;

    /**
     * 请求参数
     *
     * @type {Array<KeyValuePairStringString>}
     * @memberof StressTestInput
     */
    requestParameters?: Array<KeyValuePairStringString> | null;

    /**
     * 请求头参数
     *
     * @type {{ [key: string]: string; }}
     * @memberof StressTestInput
     */
    headers?: { [key: string]: string; } | null;

    /**
     * 路径参数
     *
     * @type {{ [key: string]: string; }}
     * @memberof StressTestInput
     */
    pathParameters?: { [key: string]: string; } | null;

    /**
     * Query参数
     *
     * @type {{ [key: string]: string; }}
     * @memberof StressTestInput
     */
    _queryParameters?: { [key: string]: string; } | null;
}
