/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 系统用户扩展机构表
 *
 * @export
 * @interface SysUserExtOrg
 */
export interface SysUserExtOrg {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof SysUserExtOrg
     */
    id?: number;

    /**
     * 用户Id
     *
     * @type {number}
     * @memberof SysUserExtOrg
     */
    userId?: number;

    /**
     * 机构Id
     *
     * @type {number}
     * @memberof SysUserExtOrg
     */
    orgId?: number;

    /**
     * 职位Id
     *
     * @type {number}
     * @memberof SysUserExtOrg
     */
    posId?: number;

    /**
     * 工号
     *
     * @type {string}
     * @memberof SysUserExtOrg
     */
    jobNum?: string | null;

    /**
     * 职级
     *
     * @type {string}
     * @memberof SysUserExtOrg
     */
    posLevel?: string | null;

    /**
     * 入职日期
     *
     * @type {Date}
     * @memberof SysUserExtOrg
     */
    joinDate?: Date | null;
}
