/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SysWxOpenUploadAvatarBody
 */
export interface SysWxOpenUploadAvatarBody {

    /**
     * 小程序用户身份标识
     *
     * @type {string}
     * @memberof SysWxOpenUploadAvatarBody
     */
    openId: string;

    /**
     * 文件
     *
     * @type {Blob}
     * @memberof SysWxOpenUploadAvatarBody
     */
    file: Blob;

    /**
     * 文件类型
     *
     * @type {string}
     * @memberof SysWxOpenUploadAvatarBody
     */
    fileType?: string;

    /**
     * 文件路径
     *
     * @type {string}
     * @memberof SysWxOpenUploadAvatarBody
     */
    path?: string;
}
