/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SysFileUploadFileBody
 */
export interface SysFileUploadFileBody {

    /**
     * 文件
     *
     * @type {Blob}
     * @memberof SysFileUploadFileBody
     */
    file: Blob;

    /**
     * 文件类别
     *
     * @type {string}
     * @memberof SysFileUploadFileBody
     */
    fileType?: string;

    /**
     * 是否公开
     *
     * @type {boolean}
     * @memberof SysFileUploadFileBody
     */
    isPublic?: boolean;

    /**
     * 允许格式：.jpeg.jpg.png.bmp.gif.tif
     *
     * @type {string}
     * @memberof SysFileUploadFileBody
     */
    allowSuffix?: string;

    /**
     * 指定存储桶名称
     *
     * @type {string}
     * @memberof SysFileUploadFileBody
     */
    bucketName?: string;

    /**
     * 指定存储提供者ID
     *
     * @type {number}
     * @memberof SysFileUploadFileBody
     */
    providerId?: number;
}
