/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 租户类型枚举<br />&nbsp;ID隔离 Id = 0<br />&nbsp;库隔离 Db = 1<br />
 * @export
 * @enum {string}
 */
export enum TenantTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}

