/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * component更新输入参数
 *
 * @export
 * @interface UpdateCmsComponentInput
 */
export interface UpdateCmsComponentInput {

    /**
     * 主键Id
     *
     * @type {number}
     * @memberof UpdateCmsComponentInput
     */
    id: number;

    /**
     * PageId
     *
     * @type {number}
     * @memberof UpdateCmsComponentInput
     */
    pageId: number;

    /**
     * ComponentTypeId
     *
     * @type {number}
     * @memberof UpdateCmsComponentInput
     */
    componentTypeId: number;

    /**
     * Pid
     *
     * @type {number}
     * @memberof UpdateCmsComponentInput
     */
    pid: number;

    /**
     * Props
     *
     * @type {string}
     * @memberof UpdateCmsComponentInput
     */
    props: string;

    /**
     * Styles
     *
     * @type {string}
     * @memberof UpdateCmsComponentInput
     */
    styles?: string | null;

    /**
     * SortOrder
     *
     * @type {number}
     * @memberof UpdateCmsComponentInput
     */
    sortOrder: number;

    /**
     * IsVisible
     *
     * @type {boolean}
     * @memberof UpdateCmsComponentInput
     */
    isVisible: boolean;

    /**
     * DeleteTime
     *
     * @type {Date}
     * @memberof UpdateCmsComponentInput
     */
    deleteTime?: Date | null;
}
