/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { StatusEnum } from './status-enum';
import { SysDictData } from './sys-dict-data';
import { YesNoEnum } from './yes-no-enum';
 /**
 * 
 *
 * @export
 * @interface UpdateDictTypeInput
 */
export interface UpdateDictTypeInput {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof UpdateDictTypeInput
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof UpdateDictTypeInput
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof UpdateDictTypeInput
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof UpdateDictTypeInput
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof UpdateDictTypeInput
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof UpdateDictTypeInput
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof UpdateDictTypeInput
     */
    updateUserName?: string | null;

    /**
     * 名称
     *
     * @type {string}
     * @memberof UpdateDictTypeInput
     */
    name: string;

    /**
     * 编码
     *
     * @type {string}
     * @memberof UpdateDictTypeInput
     */
    code: string;

    /**
     * 排序
     *
     * @type {number}
     * @memberof UpdateDictTypeInput
     */
    orderNo?: number;

    /**
     * 备注
     *
     * @type {string}
     * @memberof UpdateDictTypeInput
     */
    remark?: string | null;

    /**
     * @type {StatusEnum}
     * @memberof UpdateDictTypeInput
     */
    status?: StatusEnum;

    /**
     * 字典值集合
     *
     * @type {Array<SysDictData>}
     * @memberof UpdateDictTypeInput
     */
    children?: Array<SysDictData> | null;

    /**
     * @type {YesNoEnum}
     * @memberof UpdateDictTypeInput
     */
    isTenant?: YesNoEnum;

    /**
     * @type {YesNoEnum}
     * @memberof UpdateDictTypeInput
     */
    sysFlag?: YesNoEnum;
}
