/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 系统用户菜单快捷导航输入
 *
 * @export
 * @interface UserMenuInput
 */
export interface UserMenuInput {

    /**
     * 收藏菜单Id集合
     *
     * @type {Array<number>}
     * @memberof UserMenuInput
     */
    menuIdList?: Array<number> | null;
}
