/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 授权用户角色
 *
 * @export
 * @interface UserRoleInput
 */
export interface UserRoleInput {

    /**
     * 用户Id
     *
     * @type {number}
     * @memberof UserRoleInput
     */
    userId?: number;

    /**
     * 角色Id集合
     *
     * @type {Array<number>}
     * @memberof UserRoleInput
     */
    roleIdList?: Array<number> | null;
}
