/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface WechatPayRefundDomesticInput
 */
export interface WechatPayRefundDomesticInput {

    /**
     * 商户端生成的业务流水号
     *
     * @type {string}
     * @memberof WechatPayRefundDomesticInput
     */
    tradeId: string;

    /**
     * 退款原因
     *
     * @type {string}
     * @memberof WechatPayRefundDomesticInput
     */
    reason?: string | null;

    /**
     * 退款金额
     *
     * @type {number}
     * @memberof WechatPayRefundDomesticInput
     */
    refund: number;

    /**
     * 原订单金额
     *
     * @type {number}
     * @memberof WechatPayRefundDomesticInput
     */
    total: number;
}
