/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 周枚举<br />&nbsp;周一 Monday = 1<br />&nbsp;周二 Tuesday = 2<br />&nbsp;周三 Wednesday = 3<br />&nbsp;周四 Thursday = 4<br />&nbsp;周五 Friday = 5<br />&nbsp;周六 Saturday = 6<br />&nbsp;周日 Sunday = 7<br />
 * @export
 * @enum {string}
 */
export enum WeekEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7
}

